### ISSUE TITLE
cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by jorge8989** [froala/wysiwyg-rails#34] opened 2016-05-27 14:36 UTC
Hello,
i get this error when initializing the editor

```
cannot read property 'bind' of undefined
```

![selection_247](https://cloud.githubusercontent.com/assets/11651398/15610960/0da0498e-23f6-11e6-9a1f-59497a896c98.png)

The editor is initialized, and it works fine, but think i should not have that error message.

It seems like the undefined variable/object is 'tooltip'

![selection_248](https://cloud.githubusercontent.com/assets/11651398/15611061/8bca8540-23f6-11e6-8bdb-1461dc8cb948.png)

Any idea to fix this problem?

Thanks.

**Comment by jorge8989** [comment] 2016-05-27 15:05
This is with the version 2.3.0, i'm using the version 2.2.4 now to avoid this issue

**Comment by stefanneculai** [comment] 2016-05-30 09:31
We cannot reproduce this at our end. Could you please make a jsFiddle or send us a link to the page where you have this problem? You can contact us via our website. Thank you.

**Comment by eterry1388** [comment] 2016-11-01 18:33
Might be related.  I'm getting `Uncaught TypeError: Cannot read property 'nodeName' of undefined`

**Comment by stefanneculai** [comment] 2017-01-26 12:58
@jorge8989 this should be fixed in V2.4.1, the current version.

**Closed by stefanneculai** 2017-01-26 12:58 UTC
